version: '3.5'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8050:8000"
    volumes:
      - .:/code/
    command: python manage.py runserver 0.0.0.0:8000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./media:/media/
      - ./static:/code/static/
    depends_on:
      - rabbitmq
    command: celery -A djangoProject worker


  postgres:
    image: postgres:9.6
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"