# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 12:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time_to_start', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, '\u0421\u043e\u0437\u0434\u0430\u043d\u043e'), (1, '\u0417\u0430\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u043e'), (2, '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u0435\u0442\u0441\u044f'), (3, '\u041f\u043e\u043b\u0443\u0447\u0435\u043d\u043e'), (4, '\u041e\u0448\u0438\u0431\u043a\u0430'), (5, '\u0423\u0441\u043f\u0435\u0448\u043d\u043e')], default=0)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0438 \u043d\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0443',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438 \u043d\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0443',
            },
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='html_text',
            field=models.FileField(blank=True, upload_to='messages/', verbose_name='\u0424\u0430\u0439\u043b \u0448\u0430\u0431\u043b\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='\u0422\u0443\u0442 \u043c\u043e\u0436\u043d\u043e \u043d\u0430\u043f\u0438\u0441\u0430\u0442\u044c \u0448\u0430\u0431\u043b\u043e\u043d, \u041d\u041e! \u043f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0442\u0443\u0442 \u0440\u0443\u0441\u0441\u043a\u0438\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b, \u0441\u0435\u0433\u043e\u0434\u043d\u044f \u043d\u0435 \u0445\u043e\u0447\u0435\u0442\u0441\u044f \u0440\u0430\u0437\u0431\u0438\u0440\u0430\u0442\u044c\u0441\u044f \u0441 \u043a\u043e\u0434\u0438\u0440\u043e\u0432\u043a\u0430\u043c\u0438', verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a/\u0422\u0435\u043c\u0430 \u043f\u0438\u0441\u044c\u043c\u0430'),
        ),
        migrations.AddField(
            model_name='sendingtask',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MessageModel'),
        ),
        migrations.AddField(
            model_name='sendingtask',
            name='receivers',
            field=models.ManyToManyField(to='main.Receiver'),
        ),
    ]
